Repository Abhay-hack/Lumina, pull requests merged in 2025-01, with the labels that each got.

#28 Feat. Fix #27 Added Search functionality
  public/jobs.html
Labels: good first issue, BEGINNER, SWOC

#31 Add contact us page
  public/contactUs.html
  public/index.html
Labels: enhancement, good first issue, BEGINNER, SWOC, SWOC 2025

#50 Implemented Hover Effect to Automatically Display FAQ Answers
  public/index.css
Labels: good first issue, BEGINNER, SWOC, SWOC 2025

#58 corrected mentorships spelling in main heading
  public/index.html
Labels: bug, good first issue, BEGINNER, SWOC, SWOC 2025

#57 Home button added
  public/index.html
  public/internships.html
  public/jobs.html
  public/mentorship.html
Labels: good first issue, BEGINNER, SWOC, SWOC 2025

#49 Add eye toggle for password visibility
  public/image/eye-slash.svg
  public/image/eye.svg
  public/login.css
  public/login.html
  public/signup.html
Labels: good first issue, BEGINNER, SWOC, SWOC 2025

#59 Design improvement
  public/index.css
  public/index.html
Labels: good first issue, BEGINNER, SWOC, SWOC 2025

#67 Add animation
  public/image/OIP (5).jpeg
  public/image/OIP (7).jpeg
  public/image/OIP (8).jpeg
  public/index.css
  public/index.html
  public/testimonial.css
Labels: good first issue, BEGINNER, SWOC, SWOC 2025

#56 internships & mentorships pages redesigned
  public/internships.css
  public/internships.html
  public/mentorship.css
  public/mentorship.html
Labels: enhancement, BEGINNER, SWOC, SWOC 2025

#60 Added Page for Events & Webinar Update
  public/events&webinar.css
  public/events&webinar.html
  public/index.html
  public/internships.html
  public/jobs.html
  public/mentorship.html
Labels: enhancement, good first issue, BEGINNER, SWOC, SWOC 2025

#72 #1 Cards issue resolved
  public/internships.css
  public/internships.html
Labels: enhancement, SWOC, INTERMEDIATE, SWOC 2025

#48 #1 card styled
  public/internships.css
  public/internships.html
Labels: enhancement, SWOC, INTERMEDIATE, SWOC 2025

#69 Created resouces section and added resouces and practice pages.
  public/index.html
  public/internships.html
  public/jobs.html
  public/mentorship.html
  public/resources.css
  public/resources.html
Labels: enhancement, SWOC, INTERMEDIATE, SWOC 2025

#46 Fixes the Issues in Mentorship and Internship pages
  public/internships.css
  public/mentorship.css
Labels: bug, good first issue, BEGINNER, SWOC, SWOC 2025

#87 Add Chatbot Integration to Enhance User Engagement and Support
  public/index.html
  public/internships.css
  public/internships.html
  public/jobs.html
  public/mentorship.html
  public/resources.html
  public/script.js
Labels: BEGINNER, SWOC, SWOC 2025

#68 Add name validation for signup form
  public/validation.js
Labels: bug, BEGINNER, SWOC, SWOC 2025

#90 social media icons added
  public/index.html
Labels: BEGINNER, SWOC, SWOC 2025

#89 fixed navbars for all pages
  public/events&webinar.css
  public/events&webinar.html
  public/index.css
  public/internships.css
  public/internships.html
  public/jobs.css
  public/jobs.html
  public/mentorship.css
  public/mentorship.html
  public/resources.css
  public/resources.html
Labels: SWOC, INTERMEDIATE, SWOC 2025

#100 fixed homemain heading overflow using flex wrap - Closes #99
  public/index.css
Labels: good first issue, BEGINNER, SWOC, SWOC 2025

#104 Add custom error page with styling for 404 errors
  public/error.css
  public/error.html
Labels: enhancement, good first issue, BEGINNER, SWOC, SWOC 2025

#107 Fixed Restructing the Landing Page UI and CSS
  public/index.css
  public/index.html
  public/testimonial.css
Labels: BEGINNER, SWOC, SWOC 2025

#116 Fixes #76 Added a contact us page
  public/contact.css
  public/contact.html
  public/contact.js
  public/index.html
Labels: enhancement, SWOC, INTERMEDIATE, SWOC 2025

#126 Changes made in website like add forgot password page
  .vscode/settings.json
  public/events&webinar.css
  public/events&webinar.html
  public/forgot-password.css
  public/forgot-password.html
  public/forgot-password.js
  public/image/Inspirational-Exams-Quotes-For-Students.jpg
  public/image/Inspirational-picture-Quote-for-Student.jpg
  public/index.css
  public/index.html
  public/internships.css
  public/internships.html
  public/jobs.css
  public/jobs.html
  public/login.html
  public/mentorship.css
  public/mentorship.html
  public/resources.css
  public/script.js
Labels: enhancement, SWOC, SWOC 2025, ADVANCED

#117 Remove duplicates in main section
  public/AllmediaLts.html
  public/ITWorlds.html
  public/ITinfosy.html
  public/InfoStatics.html
  public/image/css3-logo-png-transparent.png
  public/image/html.webp
  public/image/java.jpg
  public/image/php.jpg
  public/index.html
  public/jobs.css
  public/jobs.html
  public/massIdea.html
  public/softwareSolution.html
Labels: BEGINNER, SWOC, SWOC 2025

#146 Lumina New Pages Add
  public/AddEvent.html
  public/Apply.html
  public/PostIntern.html
  public/PostJob.html
  public/Register.html
  public/events&webinar.html
  public/index.css
  public/index.html
  public/internships.html
  public/jobs.html
  public/mentorship.html
Labels: SWOC, SWOC 2025, ADVANCED

#142 footer section added to the resources page
  public/resources.css
  public/resources.html
Labels: BEGINNER, SWOC, SWOC 2025

#151 navbar added to post an internship page
  public/PostIntern.css
  public/PostIntern.html
Labels: BEGINNER, SWOC, SWOC 2025

#162 Responsive FAQ section
  package-lock.json
  public/index.css
Labels: BEGINNER, SWOC, SWOC 2025

#160 navbar added to mentorship and event/webinar page
  public/AddEvent.html
  public/Apply.html
Labels: BEGINNER, SWOC, SWOC 2025

#113 Add jobs
  public/AllmediaLts.html
  public/ITWorlds.html
  public/ITinfosy.html
  public/InfoStatics.html
  public/jobs.css
  public/jobs.html
  public/jobs.js
  public/massIdea.html
  public/softwareSolution.html
Labels: SWOC, SWOC 2025, ADVANCED

#182 footer added to event webinar page
  public/events&webinar.css
  public/events&webinar.html
Labels: BEGINNER, SWOC, SWOC 2025

#181 Issue No. #88 [FIXED] Scroll To Top Button Added.
  public/index.css
  public/index.html
  public/scrollTop.js
Labels: BEGINNER, SWOC, SWOC 2025

#183 Issue No. #174 [FIXED] On Resources page Practice links heading should be in Center.
  public/index.html
  public/resources.css
Labels: BEGINNER, SWOC, SWOC 2025

#172 Apply Page link
  public/AllmediaLts.html
  public/ITWorlds.html
  public/ITinfosy.html
  public/InfoStatics.html
  public/index.html
  public/internships.html
  public/jobs.css
  public/massIdea.html
  public/softwareSolution.html
Labels: SWOC, INTERMEDIATE, SWOC 2025

#189 🔄 Added Scroll Button to Multiple Pages for Seamless Navigation
  public/events&webinar.css
  public/events&webinar.html
  public/internships.css
  public/internships.html
  public/jobs.css
  public/jobs.html
  public/mentorship.css
  public/mentorship.html
  public/resources.css
  public/resources.html
Labels: BEGINNER, SWOC, SWOC 2025
